'use strict';
/*
* List of countries and their codes
* TODO: delete this controller when confirmed as we are now using /generics/locales endpoint
*/
angular.module('mobius.controllers.common.isoCountries', [])

.controller( 'ISOCountriesCtrl', function($scope) {
  var countries = [
    {code:'CAN',title:'Canada'},
    {code:'USA',title:'United States'},
    {code:'GBR',title:'United Kingdom'},
    {code:'AFG',title:'Afghanistan'},
    {code:'ALA',title:'Åland Islands'},
    {code:'ALB',title:'Albania'},
    {code:'DZA',title:'Algeria'},
    {code:'ASM',title:'American Samoa'},
    {code:'AND',title:'Andorra'},
    {code:'AGO',title:'Angola'},
    {code:'AIA',title:'Anguilla'},
    {code:'ATA',title:'Antarctica'},
    {code:'ATG',title:'Antigua and Barbuda'},
    {code:'ARG',title:'Argentina'},
    {code:'ARM',title:'Armenia'},
    {code:'ABW',title:'Aruba'},
    {code:'AUS',title:'Australia'},
    {code:'AUT',title:'Austria'},
    {code:'AZE',title:'Azerbaijan'},
    {code:'BHS',title:'Bahamas'},
    {code:'BHR',title:'Bahrain'},
    {code:'BGD',title:'Bangladesh'},
    {code:'BRB',title:'Barbados'},
    {code:'BLR',title:'Belarus'},
    {code:'BEL',title:'Belgium'},
    {code:'BLZ',title:'Belize'},
    {code:'BEN',title:'Benin'},
    {code:'BMU',title:'Bermuda'},
    {code:'BTN',title:'Bhutan'},
    {code:'BOL',title:'Bolivia, Plurinational State of'},
    {code:'BES',title:'Bonaire, Sint Eustatius and Saba'},
    {code:'BIH',title:'Bosnia and Herzegovina'},
    {code:'BWA',title:'Botswana'},
    {code:'BVT',title:'Bouvet Island'},
    {code:'BRA',title:'Brazil'},
    {code:'IOT',title:'British Indian Ocean Territory'},
    {code:'BRN',title:'Brunei Darussalam'},
    {code:'BGR',title:'Bulgaria'},
    {code:'BFA',title:'Burkina Faso'},
    {code:'BDI',title:'Burundi'},
    {code:'KHM',title:'Cambodia'},
    {code:'CMR',title:'Cameroon'},
    {code:'CPV',title:'Cape Verde'},
    {code:'CYM',title:'Cayman Islands'},
    {code:'CAF',title:'Central African Republic'},
    {code:'TCD',title:'Chad'},
    {code:'CHL',title:'Chile'},
    {code:'CHN',title:'China'},
    {code:'CXR',title:'Christmas Island'},
    {code:'CCK',title:'Cocos (Keeling) Islands'},
    {code:'COL',title:'Colombia'},
    {code:'COM',title:'Comoros'},
    {code:'COG',title:'Congo'},
    {code:'COD',title:'Congo, the Democratic Republic of the'},
    {code:'COK',title:'Cook Islands'},
    {code:'CRI',title:'Costa Rica'},
    {code:'CIV',title:'Côte dIvoire'},
    {code:'HRV',title:'Croatia'},
    {code:'CUB',title:'Cuba'},
    {code:'CUW',title:'Curaçao'},
    {code:'CYP',title:'Cyprus'},
    {code:'CZE',title:'Czech Republic'},
    {code:'DNK',title:'Denmark'},
    {code:'DJI',title:'Djibouti'},
    {code:'DMA',title:'Dominica'},
    {code:'DOM',title:'Dominican Republic'},
    {code:'ECU',title:'Ecuador'},
    {code:'EGY',title:'Egypt'},
    {code:'SLV',title:'El Salvador'},
    {code:'GNQ',title:'Equatorial Guinea'},
    {code:'ERI',title:'Eritrea'},
    {code:'EST',title:'Estonia'},
    {code:'ETH',title:'Ethiopia'},
    {code:'FLK',title:'Falkland Islands (Malvinas)'},
    {code:'FRO',title:'Faroe Islands'},
    {code:'FJI',title:'Fiji'},
    {code:'FIN',title:'Finland'},
    {code:'FRA',title:'France'},
    {code:'GUF',title:'French Guiana'},
    {code:'PYF',title:'French Polynesia'},
    {code:'ATF',title:'French Southern Territories'},
    {code:'GAB',title:'Gabon'},
    {code:'GMB',title:'Gambia'},
    {code:'GEO',title:'Georgia'},
    {code:'DEU',title:'Germany'},
    {code:'GHA',title:'Ghana'},
    {code:'GIB',title:'Gibraltar'},
    {code:'GRC',title:'Greece'},
    {code:'GRL',title:'Greenland'},
    {code:'GRD',title:'Grenada'},
    {code:'GLP',title:'Guadeloupe'},
    {code:'GUM',title:'Guam'},
    {code:'GTM',title:'Guatemala'},
    {code:'GGY',title:'Guernsey'},
    {code:'GIN',title:'Guinea'},
    {code:'GNB',title:'Guinea-Bissau'},
    {code:'GUY',title:'Guyana'},
    {code:'HTI',title:'Haiti'},
    {code:'HMD',title:'Heard Island and McDonald Islands'},
    {code:'VAT',title:'Holy See (Vatican City State)'},
    {code:'HND',title:'Honduras'},
    {code:'HKG',title:'Hong Kong'},
    {code:'HUN',title:'Hungary'},
    {code:'ISL',title:'Iceland'},
    {code:'IND',title:'India'},
    {code:'IDN',title:'Indonesia'},
    {code:'IRN',title:'Iran, Islamic Republic of'},
    {code:'IRQ',title:'Iraq'},
    {code:'IRL',title:'Ireland'},
    {code:'IMN',title:'Isle of Man'},
    {code:'ISR',title:'Israel'},
    {code:'ITA',title:'Italy'},
    {code:'JAM',title:'Jamaica'},
    {code:'JPN',title:'Japan'},
    {code:'JEY',title:'Jersey'},
    {code:'JOR',title:'Jordan'},
    {code:'KAZ',title:'Kazakhstan'},
    {code:'KEN',title:'Kenya'},
    {code:'KIR',title:'Kiribati'},
    {code:'PRK',title:'Korea, Democratic Peoples Republic of'},
    {code:'KOR',title:'Korea, Republic of'},
    {code:'KWT',title:'Kuwait'},
    {code:'KGZ',title:'Kyrgyzstan'},
    {code:'LAO',title:'Lao Peoples Democratic Republic'},
    {code:'LVA',title:'Latvia'},
    {code:'LBN',title:'Lebanon'},
    {code:'LSO',title:'Lesotho'},
    {code:'LBR',title:'Liberia'},
    {code:'LBY',title:'Libya'},
    {code:'LIE',title:'Liechtenstein'},
    {code:'LTU',title:'Lithuania'},
    {code:'LUX',title:'Luxembourg'},
    {code:'MAC',title:'Macao'},
    {code:'MKD',title:'Macedonia, the former Yugoslav Republic of'},
    {code:'MDG',title:'Madagascar'},
    {code:'MWI',title:'Malawi'},
    {code:'MYS',title:'Malaysia'},
    {code:'MDV',title:'Maldives'},
    {code:'MLI',title:'Mali'},
    {code:'MLT',title:'Malta'},
    {code:'MHL',title:'Marshall Islands'},
    {code:'MTQ',title:'Martinique'},
    {code:'MRT',title:'Mauritania'},
    {code:'MUS',title:'Mauritius'},
    {code:'MYT',title:'Mayotte'},
    {code:'MEX',title:'Mexico'},
    {code:'FSM',title:'Micronesia, Federated States of'},
    {code:'MDA',title:'Moldova, Republic of'},
    {code:'MCO',title:'Monaco'},
    {code:'MNG',title:'Mongolia'},
    {code:'MNE',title:'Montenegro'},
    {code:'MSR',title:'Montserrat'},
    {code:'MAR',title:'Morocco'},
    {code:'MOZ',title:'Mozambique'},
    {code:'MMR',title:'Myanmar'},
    {code:'NAM',title:'Namibia'},
    {code:'NRU',title:'Nauru'},
    {code:'NPL',title:'Nepal'},
    {code:'NLD',title:'Netherlands'},
    {code:'NCL',title:'New Caledonia'},
    {code:'NZL',title:'New Zealand'},
    {code:'NIC',title:'Nicaragua'},
    {code:'NER',title:'Niger'},
    {code:'NGA',title:'Nigeria'},
    {code:'NIU',title:'Niue'},
    {code:'NFK',title:'Norfolk Island'},
    {code:'MNP',title:'Northern Mariana Islands'},
    {code:'NOR',title:'Norway'},
    {code:'OMN',title:'Oman'},
    {code:'PAK',title:'Pakistan'},
    {code:'PLW',title:'Palau'},
    {code:'PSE',title:'Palestinian Territory, Occupied'},
    {code:'PAN',title:'Panama'},
    {code:'PNG',title:'Papua New Guinea'},
    {code:'PRY',title:'Paraguay'},
    {code:'PER',title:'Peru'},
    {code:'PHL',title:'Philippines'},
    {code:'PCN',title:'Pitcairn'},
    {code:'POL',title:'Poland'},
    {code:'PRT',title:'Portugal'},
    {code:'PRI',title:'Puerto Rico'},
    {code:'QAT',title:'Qatar'},
    {code:'REU',title:'Réunion'},
    {code:'ROU',title:'Romania'},
    {code:'RUS',title:'Russian Federation'},
    {code:'RWA',title:'Rwanda'},
    {code:'BLM',title:'Saint Barthélemy'},
    {code:'SHN',title:'Saint Helena, Ascension and Tristan da Cunha'},
    {code:'KNA',title:'Saint Kitts and Nevis'},
    {code:'LCA',title:'Saint Lucia'},
    {code:'MAF',title:'Saint Martin (French part)'},
    {code:'SPM',title:'Saint Pierre and Miquelon'},
    {code:'VCT',title:'Saint Vincent and the Grenadines'},
    {code:'WSM',title:'Samoa'},
    {code:'SMR',title:'San Marino'},
    {code:'STP',title:'Sao Tome and Principe'},
    {code:'SAU',title:'Saudi Arabia'},
    {code:'SEN',title:'Senegal'},
    {code:'SRB',title:'Serbia'},
    {code:'SYC',title:'Seychelles'},
    {code:'SLE',title:'Sierra Leone'},
    {code:'SGP',title:'Singapore'},
    {code:'SXM',title:'Sint Maarten (Dutch part)'},
    {code:'SVK',title:'Slovakia'},
    {code:'SVN',title:'Slovenia'},
    {code:'SLB',title:'Solomon Islands'},
    {code:'SOM',title:'Somalia'},
    {code:'ZAF',title:'South Africa'},
    {code:'SGS',title:'South Georgia and the South Sandwich Islands'},
    {code:'SSD',title:'South Sudan'},
    {code:'ESP',title:'Spain'},
    {code:'LKA',title:'Sri Lanka'},
    {code:'SDN',title:'Sudan'},
    {code:'SUR',title:'Suriname'},
    {code:'SJM',title:'Svalbard and Jan Mayen'},
    {code:'SWZ',title:'Swaziland'},
    {code:'SWE',title:'Sweden'},
    {code:'CHE',title:'Switzerland'},
    {code:'SYR',title:'Syrian Arab Republic'},
    {code:'TWN',title:'Taiwan, Province of China'},
    {code:'TJK',title:'Tajikistan'},
    {code:'TZA',title:'Tanzania, United Republic of'},
    {code:'THA',title:'Thailand'},
    {code:'TLS',title:'Timor-Leste'},
    {code:'TGO',title:'Togo'},
    {code:'TKL',title:'Tokelau'},
    {code:'TON',title:'Tonga'},
    {code:'TTO',title:'Trinidad and Tobago'},
    {code:'TUN',title:'Tunisia'},
    {code:'TUR',title:'Turkey'},
    {code:'TKM',title:'Turkmenistan'},
    {code:'TCA',title:'Turks and Caicos Islands'},
    {code:'TUV',title:'Tuvalu'},
    {code:'UGA',title:'Uganda'},
    {code:'UKR',title:'Ukraine'},
    {code:'ARE',title:'United Arab Emirates'},
    {code:'UMI',title:'United States Minor Outlying Islands'},
    {code:'URY',title:'Uruguay'},
    {code:'UZB',title:'Uzbekistan'},
    {code:'VUT',title:'Vanuatu'},
    {code:'VEN',title:'Venezuela, Bolivarian Republic of'},
    {code:'VNM',title:'Viet Nam'},
    {code:'VGB',title:'Virgin Islands, British'},
    {code:'VIR',title:'Virgin Islands, U.S.'},
    {code:'WLF',title:'Wallis and Futuna'},
    {code:'ESH',title:'Western Sahara'},
    {code:'YEM',title:'Yemen'},
    {code:'ZMB',title:'Zambia'},
    {code:'ZWE',title:'Zimbabwe'}
  ];

  $scope.iso = {
    countries: countries
  };
});
