---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
exclude_paths:
- config/
- tests/
- vendors/
- src/targets/**/settings.js
- build/
- compile/
- coverage/
- bower_components/
- karma/
